### ISSUE TITLE
Quick modification of squashfs

### ISSUE THREAD

**Issue by dani1993l** [AgentD/squashfs-tools-ng#105]
Hi all,
I am new to the squashfs world and was wondering if there was a way to quickly add a file to a non-root directory of a given squashfs image, without mounting and recompressing the image. I found such a discussion on [stakcexchange](https://unix.stackexchange.com/questions/375191/append-to-sub-directory-inside-squashfs-file), though I hoped I could get a more technical answer regarding the possibility of such an implementation - Is it possible? How would one approach such a task? Is there a  reason why this has not yet been implemented that I am missing?

Any light shed on this issue would be very appreciated, as I am considering attempting to implement this myself.
Thanks and apologies if this is not the place for such an inquiry

**Comment by AgentD** [comment]
Closing this and referring to the detailed explanation in https://github.com/plougher/squashfs-tools/issues/174
