### ISSUE TITLE
user experience: unintelligible prose fragment

### ISSUE THREAD

**Issue by Steve-Newcomb** [AgentD/squashfs-tools-ng#108]
output from gensquashfs:

"Out of which where fragment blocks: 39613"

What does this mean?  Maybe it means,

"Fragment blocks included in the above: 39613"

?

**Comment by AgentD** [comment]
The "where" is a glaring typo I apparently never caught so far and should be "were". Commit f3d87d9 takes care of that.

And yes, it is supposed to mean exactly what you suggest it means.

I guess I semi-consciously based it on food labeling. Similar to the drink bottle on my desk stating something to the effect of "carbohydrates: X g, out of which are sugar: Y g", but it's labeled in my native German, which now makes me wonder if there's something wrong with paraphrasing it in English like I did?

Tickling Google the right way produces excerpts from literature using the same phrasing, but they seem to be predominantly chemistry books? Not sure if I can use chemistry as an example for normal use of language ("To the SquashFS was a then added X fragment blocks").
