### ISSUE TITLE
Creating image with certain input data & options - "packing file data: data corrupted"

### ISSUE THREAD

**Issue by benkohler** [AgentD/squashfs-tools-ng#110]
We began getting this gensquashfs error on a large (~4GB) squashfs image for the rootfs of our livecd.  I've reduced the test case down to a specific subdir, to be able to reproduce & test much more quickly.  Example run:

$ gensquashfs -fqD gensquashfs-test-case/ test.img
man3/ASN1_OBJECT_new.3ssl.bz2: packing file data: data corrupted.

Strangely, it seems to only fail with the default block size, I tried a bunch of other block sizes and it succeeds:

$ gensquashfs -fqD gensquashfs-test-case/ test.img -b 4096
$ gensquashfs -fqD gensquashfs-test-case/ test.img -b 8192
$ gensquashfs -fqD gensquashfs-test-case/ test.img -b 16384
$ gensquashfs -fqD gensquashfs-test-case/ test.img -b 32768
$ gensquashfs -fqD gensquashfs-test-case/ test.img -b 65536
$ gensquashfs -fqD gensquashfs-test-case/ test.img -b 131072
man3/BIO_should_retry.3ssl.bz2: packing file data: data corrupted.
$ gensquashfs -fqD gensquashfs-test-case/ test.img -b 262144
$

Also I'm able to get it to succeed with default block size if I turn up the job count high enough:

$ gensquashfs -fqD gensquashfs-test-case/ test.img
man3/ASN1_OBJECT_new.3ssl.bz2: packing file data: data corrupted.
 gensquashfs -fqD gensquashfs-test-case/ test.img -j2
man2/pipe.2.bz2: packing file data: data corrupted.
$ gensquashfs -fqD gensquashfs-test-case/ test.img -j0
man2/pciconfig_iobase.2: packing file data: data corrupted.
$ gensquashfs -fqD gensquashfs-test-case/ test.img -j20
man3/CMSG_ALIGN.3: packing file data: data corrupted.
$ gensquashfs -fqD gensquashfs-test-case/ test.img -j200
$

One more interesting thing is that even though I am routinely seeing 'data corrupted' in specific dirs like gensquashfs-test-case/man3/, if I point gensquashfs at that specific dir, it doesn't fail.

I'm going to try to attach a tarball of the test data you can use to reproduce.

**Comment by benkohler** [comment]
The current smallest test tarball I can make won't fit in the 25MB limit, here's a link to download it from google drive, I will work to make an even more reduced test case:
https://drive.google.com/file/d/1FvKLUHFbquyFTqkPztKl8f8AbWRTbPs0/view?usp=share_link

**Comment by benkohler** [comment]
[gensquashfs-test-case.tar.gz](https://github.com/AgentD/squashfs-tools-ng/files/10033345/gensquashfs-test-case.tar.gz)

**Comment by benkohler** [comment]
And on all 3 of my test machines, with either the reduced test case OR the whole 4GB test case, the cutoff seems to be 22->23 jobs.

-j21 -> fail
-j22 -> fail
-j23 -> success
-j24 -> success

**Comment by AgentD** [comment]
Thanks for the reproducing samples by the way! I'll see if I can integrate them into my test suite on my end.

**Comment by benkohler** [comment]
Wow thanks for the fixes and the writeup.  I can confirm that with these latest fixes, I am unable to trigger any failure with any of the test scenarios I can throw at it.

**Comment by Dr-Emann** [comment]
Wow, what a great, thorough bug report, and a nice in-depth response explaining not only that the bug was fixed, but what exactly was happening. This is a great thread, thanks to all involved!
