### ISSUE TITLE
doc: Zeropages are not documented

### ISSUE THREAD

**Issue by Gottox** [AgentD/squashfs-tools-ng#115]
I noticed by accident, that if a data block has the size of `0`, it is considered a full block filled with zeros. This behavior is not documented in `doc/format.adoc`.

**Comment by AgentD** [comment]
Yes, sparse files are implemented this way.

This is already documented in [section 4, line 498](https://github.com/AgentD/squashfs-tools-ng/blob/master/doc/format.adoc?plain=1#L498) of `doc/format.adoc`

**Comment by Gottox** [comment]
Ah, thanks for pointing out!
