### ISSUE TITLE
Functional parity with squashfs-tools

### ISSUE THREAD

**Issue by Drsheppard01** [AgentD/squashfs-tools-ng#130]
I'm not sure if I should create this issue, as it's more of a help and advice thing

I am currently using Chimera Linux and my idea is to use a small script to get AppImage working. 
In a nutshell AppImage is ELF-Header + Squashfs
Since AppImage relies on Glibc, to unpack it, you need to calculate the size of the ELF header and unpack it using unsquashfs -o as shown in this script:

https://github.com/Phantop/appdwarf/blob/main/appdwarf#L34

Is it possible to do this and if so, how with `rdsquashfs` or `sqfs2tar`

I'm counting on all the help I can get, Dr.Sheppard

**Comment by AgentD** [comment]
Hi @Drsheppard01 ,

If I understood it correctly, the idea is to unpack a SquashFS image stored at an offset within another file?

Right now, `rdsquashfs`  does not have an option for that. You could use `dd` with the `skip=....` option to extract the image from the ELF file and then pass it to `rdsquashfs` or `sqfs2tar`.

**Comment by Drsheppard01** [comment]
Thanks for help @AgentD
