### ISSUE TITLE
squash-tools-ng 1.3.2 for windows halt squahfs file extraction with error

### ISSUE THREAD

**Issue by Hanatarou** [AgentD/squashfs-tools-ng#133]
Hello everybody,

I am currently using squash-tools-ng 1.3.2 for window and I would like to extract "filesystem.squashfs" from GParted live iso to add some drivers to it. But when using "rdsquashfs.exe" to extract it halts with error "HINT: this could be caused by case sensitivity on Windows.".

Here is the print from the error:

![image](https://github.com/user-attachments/assets/d2b41d4c-c1d4-4cca-b6c2-e5cf020912d8)

This is the command line I have used:
"C:\Users\Central\Desktop\squashfs-tools-ng\squashfs-tools-ng-1.3.2-mingw64\bin\rdsquashfs.exe" -u "/" -p "G:\Arquivos Auxiliares\Manutenção e Diagnóstico\OtherOS\System-Tools\Output" "G:\Arquivos Auxiliares\Manutenção e Diagnóstico\OtherOS\System-Tools\filesystem.squashfs"

Best regards,

Hanatarou

**Comment by Hanatarou** [comment]
Hello everybody,

After some research I fixed the previous error with the code below:

```
@echo off
:: Define the variable UNPACK_PATH with the path to the folder where the SquashFS file will be extracted
set UNPACK_PATH="%~dp1%~n1_Unpacked"

:: Check if the folder exists
if exist %UNPACK_PATH% (
    echo The folder %UNPACK_PATH% already exists. Deleting it...
    rmdir /s /q %UNPACK_PATH%
)

:: Create the folder
echo Creating the folder %UNPACK_PATH%...
mkdir %UNPACK_PATH%

:: Enable case sensitivity in the folder
echo Enabling case sensitivity for %UNPACK_PATH%...
fsutil file setCaseSensitiveInfo %UNPACK_PATH% enable

:: Verify if the case sensitivity was successfully enabled
if errorlevel 1 (
    echo ERROR: Failed to enable case sensitivity for the folder.
    exit /b 1
) else (
    echo The folder %UNPACK_PATH% now supports case sensitivity.
)

"%~dp0\bin\rdsquashfs.exe" -u "/" -p %UNPACK_PATH% %1
```
But I still need help. Now the files from the "filesystem.squashfs" root are not extracted (bin, initrd.img, lib, lib32, lib64, sbin, vmlinuz).

![image](https://github.com/user-attachments/assets/d2780cc0-e35e-4860-8c01-c1f247e63f6b)

Best regards,

Hanatarou

**Comment by Hanatarou** [comment]
Hello everybody,

The files I mentioned earlier (bin, initrd.img, lib, lib32, lib64, sbin, vmlinuz) are symlinks. How should I deal with them? Is there a way to process them?

Best regards,

Hanatarou

**Comment by AgentD** [comment]
Hi @Hanatarou ,

on Windows, `rdsquashfs` only unpacks regular files and directories. Symlinks, file permissions, etc... are not preserved. As you already discovered (and worked around), case insensitivity on Windows is another issue. Two files may have the same name, but with different case, Linux will treat them as different files, but Windows (by default) doesn't. Non-ASCII filenames are an entirely different can of worms (#96).

If you want to modify a SquashFS image on Windows, the simplest way is through manifest files.

If you run `rdsquashfs -d <sqfsfile>`, it produces a listing of all the contents, including things like symlinks or device files. The listing also explicitly specifies file permissions and ownership.

With `gensquashfs -F <listfile> <sqfsfile>` you can use this to produce a new SquashFS image from the listing. Nothing in the listing has to exist on the filesystem, the entire directory tree is re-created in memory from the list. Only regular files are loaded from disk. The list file can specify a path where to load them from. If you use the `-p` option for `rdsquashfs -d`, it already adds the path relative to the unpack directory in the listing.

Hope that helps!

**Comment by Hanatarou** [comment]
Hello @AgentD,

Thank you for your response. I am having trouble with the list part of your explanation. I used the `rdsquashfs -d <sqfsfile>` command line, but where does it save the file with the list to use in the second part? Is there an output command or a destination command?

For now, I am working like that:
```
@echo off
:: Define the variable UNPACK_PATH with the path to the folder where the SquashFS file will be extracted
set UNPACK_PATH="%~dp1%~n1_Unpacked"
set LIST_PATH="%1_FileList.txt"

:: Create the SquashFS file listing of all the contents
"%~dp0\App\bin\rdsquashfs.exe" -d -p %UNPACK_PATH% %1 >> "%LIST_PATH%"
```
Best regards,

Hanatarou

**Comment by AgentD** [comment]
> I used the `rdsquashfs -d <sqfsfile>` command line, but where does it save the file with the list to use in the second part? 
> 

it doesn't. The list is printed to `stdout`, you can redirect it into a file from the shell. I believe that is what you did in your script?

**Comment by Hanatarou** [comment]
Hello @AgentD,

Thank you for your response. That was exactly what I did in that code. I do have a last (hopefully) question: how do I pass bcj filters to "gensquashfs.exe". I tried the following code, but it didn't work:

`"%~dp0\App\bin\gensquashfs.exe" -q -F %LIST_PATH% -c xz -b 1024k -X x86 %PACK_PATH%`

Then I tried the following, but it didn't work:
`"%~dp0\App\bin\gensquashfs.exe" -q -F %LIST_PATH% -c xz -X 100%,6,3,0,2,x86 -b 1024k %PACK_PATH%`

Best regards,

Hanatarou

**Comment by AgentD** [comment]
Your command lines are missing the output file name. At the end, after all the options, you need to specify the filename of the SquashFS archive to generate.

Assuming `%PACK_PATH%` is a directory you want to pack, use the `-D` option.  The paths that the listing specifies are interpreted relative to that. If you generated the listing with `-p` you won't need that.

This works on my end:

```sh
rdsquashfs -p ./out -d ../fs/test.sqfs > list.txt
rdsquashfs -p ./out -u / -DSFLE ../fs/test.sqfs
gensquashfs -F list.txt -c xz -b 1024k -X x86 out.sqfs
```

**Comment by Hanatarou** [comment]
Hello @AgentD,

Thank you for all your help. In the end what worked for me in my end is:
```
@echo off
:: Define the variable UNPACK_PATH with the path to the folder where the SquashFS file will be extracted
set UNPACK_PATH="%~dp1%~nx1_Unpacked"

:: Define the variable PACK_PATH with the path to the file where the extracted SquashFS folder will be packed
set PACK_PATH="%~dp1%~n1_new%~x1"

:: Define the variable LIST_PATH with the path to the SquashFS file listing of all the contents
set LIST_PATH="%~dp1%~nx1_FileList.txt"

:: Pack the SquashFS folder in PACK_PATH file
echo The file %PACK_PATH% is being packed. This may take a while, please wait...
"%~dp0\App\bin\gensquashfs.exe" -q -F %LIST_PATH% -D %UNPACK_PATH% -c xz -b 1024K -X "dictsize=1024K,level=6,lc=3,lp=0,pb=2 x86" %PACK_PATH%
```

Best regards,

Hanatarou

```
