### ISSUE TITLE
LZMA support

### ISSUE THREAD

**Issue by aparcar** [AgentD/squashfs-tools-ng#17]
The source code [contains](https://github.com/AgentD/squashfs-tools-ng/blob/307107ecd2fc3ffbf6fe91497daf767700f3572f/lib/sqfs/comp/compressor.c#L38) some LZMA strings but I can't seem to activate it, please help me out

**Comment by AgentD** [comment]
The LZMA identifiers are there mainly for completeness, but LZMA support has been deliberately not implemented in favour of the improved LZMA2 format, generated by the XZ compressor.

**Comment by aparcar** [comment]
Thank you for that clarification.

**Comment by aparcar** [comment]
Could you still add LZMA(1) as it is the only supported compression by some routers bootloader?

**Comment by AgentD** [comment]
From squashfs-tools it looks like it can be done with libxz fairly easily. I will make sure to include it in the next release.

**Comment by AgentD** [comment]
Implemented in commit acce940 with a small fixup in f45b36e.

Uncompression was tested by generating an image with mksquashfs and unpacking it with rdsquashfs.

Compression was tested by generating an image with tar2sqfs and unpacking it with unsquashfs.
