### ISSUE TITLE
tar2sqfs produces garbage squashfs from mmdebstrap tarball

### ISSUE THREAD

**Issue by bdrung** [AgentD/squashfs-tools-ng#31]
When handing over a tarball produced by mmdebstrap to tar2sqfs, the output is broken:
```
mmdebstrap ["go faster" options...] buster root.tar
./tar2sqfs root.sqfs < root.tar      # generate from mmdebstrap
unsquashfs -ll root.sqfs             # squashfs-tools can't read it
mount -o loop root.sqfs /mnt         # linux 5.2 can mount it, but it's empty
file root.sqfs                       # header looks OK
rdsquashfs --describe root.sqfs      # even squashfs-tools-ng can't read it
```

```
$ rdsquashfs --describe root.sqfs
root.sqfs: reading filesystem tree: location out of bounds.
```

When booting this squashfs, the linux kernel complains:
```
[    5.134887] SQUASHFS error: Unable to read directory block [f982957:1674]
[    5.137542] SQUASHFS error: Unable to read directory block [f982957:1688]
[    5.140084] SQUASHFS error: Unable to read directory block [f982957:1688]
[    5.143930] SQUASHFS error: Unable to read directory block [f982957:1674]
[...]
```

I am using squashfs-tools-ng 0.7 on Ubuntu 19.10. I am not the only one trying this and failing. See https://bugs.debian.org/942098

**Comment by AgentD** [comment]
This might be related to #22 . Does it work with the current git master?

**Comment by bdrung** [comment]
Yes. It works with current git master. So it is a duplicate of #22.

Before I opened this bug report, I read CHANGELOG.md, but found no entry related to this bug (#22 is not mentioned there).

**Comment by AgentD** [comment]
I added the corresponding GitHub ticket numbers to the CHANGELOG.md file.
