### ISSUE TITLE
Pre-built Windows binaries don't exist

### ISSUE THREAD

**Issue by mmashwani** [AgentD/squashfs-tools-ng#35]
I don't see the pre-built Windows binaries here:
https://infraroot.at/pub/squashfs/windows/

I only see the packages for the third party libraries.

**Comment by AgentD** [comment]
Pre-built Windows binaries will be part of the upcoming 0.8 release. The previous versions do not build with mingw and 0.8 isn't out yet, so the directory is empty.

The current git master contains a build script that uses a mingw cross toolchain and should work (on my system at least) that will be used to produce the Windows binaries once the release is done.

**Comment by mmashwani** [comment]
Ah, great, thanks for the info. Looking forward to the release.
