### ISSUE TITLE
sqfs2tar some directories are missing a trailing slash

### ISSUE THREAD

**Issue by josch** [AgentD/squashfs-tools-ng#42]
Hi,

thanks for c835ac7 but some directories still don't have a trailing slash. :(

The only thing all the directories without a slash seem to have in common is that they are empty directories. I did some tests and as soon as I place something into a directory, sqfs2tar will produce the slash. Could you look into it again?

Thanks!

**Comment by josch** [comment]
Maybe the issue is, that the `is_dir` argument of `assemble_tar_path` is set by `n->children != NULL`? Maybe instead something like this has to be done:

    inode_stat(n, &sb);
    [...]
    name = assemble_tar_path(name, (sb->st_mode & S_IFMT) == S_IFDIR)

**Comment by AgentD** [comment]
Yes, the simple check whether a node has children obviously misses empty directories.

Should be fixed, 44fb01e8a8417fadd79ba347c9ad3f0bb3a1d0b8

Thanks!
