### ISSUE TITLE
gensquashfs pipe

### ISSUE THREAD

**Issue by i0x71** [AgentD/squashfs-tools-ng#46]
Hello,
Is it possible to pipe put the output of gensquashfs to stdout ?
I have half a terrabyte of files that i would like to make into a squash image and pipe them into an s3 client, storing it in a local image file would take up unneccessary space.

Thanks

**Comment by AgentD** [comment]
Unfortunately no. A SquashFS image has the meta data describing the directory tree at the end, *after* the compressed data, and the super block that describes the location of the meta data at the beginning, *before* the compressed data.

When generating a SquashFS image, you need the ability to seek back to the beginning and update the super block when you are done. This cannot be done if the output is a pipe.

This has been discussed in more detail in #24.
