### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by terpstra** [AgentD/squashfs-tools-ng#99]
I've been looking for a linkable library for writing archives in a format with wide spread tooling.

At first blush, this looks like a great option!

Do you have any benchmarks coming squashfs-tools-ng to other projects?

**Comment by AgentD** [comment]
Hi,

thanks for the appreciation! When using the library for writing files, please be aware that the library API currently still requires substantial support code on the application side. This is discussed in ticket #91 and in [squashfs-tools ticket 124](https://github.com/plougher/squashfs-tools/issues/124).

As for benchmarks, there is a benchmark in the `doc` directory ([with some fancy graphs](https://github.com/AgentD/squashfs-tools-ng/blob/master/doc/benchmark.ods)), but this has been primarily created for profiling, estimating scaling behavior and only compared to previous versions of itself.

Ticket #30 compared the performance with `mksquashfs`, but that was before the introduction of thread pool based data compression. Now that squashfs-tools has `sqfstar` implementation, it should be possible to create a comparison benchmark against `tar2sqfs`. I quickly did that when squashfs-tools 4.5 was released, but don't have any numbers to show yet. At the time I was satisfied that thanks to all the profiling/optimizing, `tar2sqfs` was faster.

Besides `squashfs-tools`, I'm not aware of any other project for *packing* SquashFS images. I could of course do some benchmarks against squashfs-tools, but I'm afraid this will only result in the typical "vendor says *their* product is better than the competition" :-)
